package com.topwave.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContractContact<M extends BaseContractContact<M>> extends Model<M> implements IBean {

	public M setContactId(java.lang.String contactId) {
		set("contact_id", contactId);
		return (M)this;
	}
	
	public java.lang.String getContactId() {
		return getStr("contact_id");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setContractId(java.lang.String contractId) {
		set("contract_id", contractId);
		return (M)this;
	}
	
	public java.lang.String getContractId() {
		return getStr("contract_id");
	}

}
