package com.topwave.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContract<M extends BaseContract<M>> extends Model<M> implements IBean {

	public M setContractId(java.lang.String contractId) {
		set("contract_id", contractId);
		return (M)this;
	}
	
	public java.lang.String getContractId() {
		return getStr("contract_id");
	}

	public M setContractNo(java.lang.String contractNo) {
		set("contract_no", contractNo);
		return (M)this;
	}
	
	public java.lang.String getContractNo() {
		return getStr("contract_no");
	}

	public M setEnterpriseId(java.lang.String enterpriseId) {
		set("enterprise_id", enterpriseId);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseId() {
		return getStr("enterprise_id");
	}

	public M setEnterpriseName(java.lang.String enterpriseName) {
		set("enterprise_name", enterpriseName);
		return (M)this;
	}
	
	public java.lang.String getEnterpriseName() {
		return getStr("enterprise_name");
	}

	public M setContractState(java.lang.String contractState) {
		set("contract_state", contractState);
		return (M)this;
	}
	
	public java.lang.String getContractState() {
		return getStr("contract_state");
	}

	public M setBuildingId(java.lang.String buildingId) {
		set("building_id", buildingId);
		return (M)this;
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_id");
	}

	public M setBuildingName(java.lang.String buildingName) {
		set("building_name", buildingName);
		return (M)this;
	}
	
	public java.lang.String getBuildingName() {
		return getStr("building_name");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setAreaSize(java.lang.String areaSize) {
		set("area_size", areaSize);
		return (M)this;
	}
	
	public java.lang.String getAreaSize() {
		return getStr("area_size");
	}

	public M setBuildingType(java.lang.String buildingType) {
		set("building_type", buildingType);
		return (M)this;
	}
	
	public java.lang.String getBuildingType() {
		return getStr("building_type");
	}

	public M setDeposit(java.lang.String deposit) {
		set("deposit", deposit);
		return (M)this;
	}
	
	public java.lang.String getDeposit() {
		return getStr("deposit");
	}

	public M setDepositUnitEnum(java.lang.String depositUnitEnum) {
		set("depositUnitEnum", depositUnitEnum);
		return (M)this;
	}
	
	public java.lang.String getDepositUnitEnum() {
		return getStr("depositUnitEnum");
	}

	public M setLeaseBeginDate(java.util.Date leaseBeginDate) {
		set("lease_begin_date", leaseBeginDate);
		return (M)this;
	}
	
	public java.util.Date getLeaseBeginDate() {
		return get("lease_begin_date");
	}

	public M setLeaseEndDate(java.util.Date leaseEndDate) {
		set("lease_end_date", leaseEndDate);
		return (M)this;
	}
	
	public java.util.Date getLeaseEndDate() {
		return get("lease_end_date");
	}

	public M setSignDate(java.util.Date signDate) {
		set("sign_date", signDate);
		return (M)this;
	}
	
	public java.util.Date getSignDate() {
		return get("sign_date");
	}

	public M setIsDel(java.lang.String isDel) {
		set("is_del", isDel);
		return (M)this;
	}
	
	public java.lang.String getIsDel() {
		return getStr("is_del");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
		return (M)this;
	}
	
	public java.util.Date getCtime() {
		return get("ctime");
	}

	public M setUtime(java.util.Date utime) {
		set("utime", utime);
		return (M)this;
	}
	
	public java.util.Date getUtime() {
		return get("utime");
	}

}
