package com.topwave.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContractRoom<M extends BaseContractRoom<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setRoomId(java.lang.String roomId) {
		set("room_id", roomId);
		return (M)this;
	}
	
	public java.lang.String getRoomId() {
		return getStr("room_id");
	}

	public M setRoomNumber(java.lang.String roomNumber) {
		set("room_number", roomNumber);
		return (M)this;
	}
	
	public java.lang.String getRoomNumber() {
		return getStr("room_number");
	}

	public M setFloor(java.lang.String floor) {
		set("floor", floor);
		return (M)this;
	}
	
	public java.lang.String getFloor() {
		return getStr("floor");
	}

	public M setPrice(java.lang.String price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.String getPrice() {
		return getStr("price");
	}

	public M setAreaSize(java.lang.String areaSize) {
		set("area_size", areaSize);
		return (M)this;
	}
	
	public java.lang.String getAreaSize() {
		return getStr("area_size");
	}

	public M setContractId(java.lang.String contractId) {
		set("contract_id", contractId);
		return (M)this;
	}
	
	public java.lang.String getContractId() {
		return getStr("contract_id");
	}

}
