package com.topwave.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBillCashFlow<M extends BaseBillCashFlow<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAction(java.lang.String action) {
		set("action", action);
		return (M)this;
	}
	
	public java.lang.String getAction() {
		return getStr("action");
	}

	public M setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
		return (M)this;
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public M setDigest(java.lang.String digest) {
		set("digest", digest);
		return (M)this;
	}
	
	public java.lang.String getDigest() {
		return getStr("digest");
	}

	public M setEnterDate(java.util.Date enterDate) {
		set("enter_date", enterDate);
		return (M)this;
	}
	
	public java.util.Date getEnterDate() {
		return get("enter_date");
	}

	public M setFlowNo(java.lang.String flowNo) {
		set("flow_no", flowNo);
		return (M)this;
	}
	
	public java.lang.String getFlowNo() {
		return getStr("flow_no");
	}

	public M setMatchId(java.lang.String matchId) {
		set("match_id", matchId);
		return (M)this;
	}
	
	public java.lang.String getMatchId() {
		return getStr("match_id");
	}

	public M setMatchedAmount(java.math.BigDecimal matchedAmount) {
		set("matched_amount", matchedAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getMatchedAmount() {
		return get("matched_amount");
	}

	public M setOtherAccount(java.lang.String otherAccount) {
		set("other_account", otherAccount);
		return (M)this;
	}
	
	public java.lang.String getOtherAccount() {
		return getStr("other_account");
	}

	public M setReceiptNo(java.lang.String receiptNo) {
		set("receipt_no", receiptNo);
		return (M)this;
	}
	
	public java.lang.String getReceiptNo() {
		return getStr("receipt_no");
	}

	public M setRemittanceMethod(java.lang.String remittanceMethod) {
		set("remittance_method", remittanceMethod);
		return (M)this;
	}
	
	public java.lang.String getRemittanceMethod() {
		return getStr("remittance_method");
	}

	public M setTenantName(java.lang.String tenantName) {
		set("tenant_name", tenantName);
		return (M)this;
	}
	
	public java.lang.String getTenantName() {
		return getStr("tenant_name");
	}

	public M setBillCashMatchId(java.lang.String billCashMatchId) {
		set("bill_cash_match_id", billCashMatchId);
		return (M)this;
	}
	
	public java.lang.String getBillCashMatchId() {
		return getStr("bill_cash_match_id");
	}

}
