package com.topwave.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBill<M extends BaseBill<M>> extends Model<M> implements IBean {

	public M setBillId(java.lang.String billId) {
		set("bill_id", billId);
		return (M)this;
	}
	
	public java.lang.String getBillId() {
		return getStr("bill_id");
	}

	public M setBillNo(java.lang.String billNo) {
		set("bill_no", billNo);
		return (M)this;
	}
	
	public java.lang.String getBillNo() {
		return getStr("bill_no");
	}

	public M setAction(java.lang.String action) {
		set("action", action);
		return (M)this;
	}
	
	public java.lang.String getAction() {
		return getStr("action");
	}

	public M setAdjustedPrimeAmount(java.math.BigDecimal adjustedPrimeAmount) {
		set("adjusted_prime_amount", adjustedPrimeAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getAdjustedPrimeAmount() {
		return get("adjusted_prime_amount");
	}

	public M setActualAmount(java.math.BigDecimal actualAmount) {
		set("actual_amount", actualAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getActualAmount() {
		return get("actual_amount");
	}

	public M setRate(java.math.BigDecimal rate) {
		set("rate", rate);
		return (M)this;
	}
	
	public java.math.BigDecimal getRate() {
		return get("rate");
	}

	public M setOverDueFineTheoryAmount(java.math.BigDecimal overDueFineTheoryAmount) {
		set("over_due_fine_theory_amount", overDueFineTheoryAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getOverDueFineTheoryAmount() {
		return get("over_due_fine_theory_amount");
	}

	public M setBillType(java.lang.String billType) {
		set("bill_type", billType);
		return (M)this;
	}
	
	public java.lang.String getBillType() {
		return getStr("bill_type");
	}

	public M setBuildingId(java.lang.String buildingId) {
		set("building_id", buildingId);
		return (M)this;
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_id");
	}

	public M setBuildingName(java.lang.String buildingName) {
		set("building_name", buildingName);
		return (M)this;
	}
	
	public java.lang.String getBuildingName() {
		return getStr("building_name");
	}

	public M setClosedStatus(java.lang.String closedStatus) {
		set("closed_status", closedStatus);
		return (M)this;
	}
	
	public java.lang.String getClosedStatus() {
		return getStr("closed_status");
	}

	public M setClosedStatusName(java.lang.String closedStatusName) {
		set("closed_status_name", closedStatusName);
		return (M)this;
	}
	
	public java.lang.String getClosedStatusName() {
		return getStr("closed_status_name");
	}

	public M setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
		return (M)this;
	}
	
	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public M setDateScope(java.lang.String dateScope) {
		set("date_scope", dateScope);
		return (M)this;
	}
	
	public java.lang.String getDateScope() {
		return getStr("date_scope");
	}

	public M setDueStatusName(java.lang.String dueStatusName) {
		set("due_status_name", dueStatusName);
		return (M)this;
	}
	
	public java.lang.String getDueStatusName() {
		return getStr("due_status_name");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setExpiredDay(java.lang.Integer expiredDay) {
		set("expired_day", expiredDay);
		return (M)this;
	}
	
	public java.lang.Integer getExpiredDay() {
		return getInt("expired_day");
	}

	public M setGeneratedReminderCount(java.lang.Integer generatedReminderCount) {
		set("generated_reminder_count", generatedReminderCount);
		return (M)this;
	}
	
	public java.lang.Integer getGeneratedReminderCount() {
		return getInt("generated_reminder_count");
	}

	public M setHandler(java.lang.String handler) {
		set("handler", handler);
		return (M)this;
	}
	
	public java.lang.String getHandler() {
		return getStr("handler");
	}

	public M setInvoiceAmount(java.lang.String invoiceAmount) {
		set("invoice_amount", invoiceAmount);
		return (M)this;
	}
	
	public java.lang.String getInvoiceAmount() {
		return getStr("invoice_amount");
	}

	public M setInvoiceStatus(java.lang.String invoiceStatus) {
		set("invoice_status", invoiceStatus);
		return (M)this;
	}
	
	public java.lang.String getInvoiceStatus() {
		return getStr("invoice_status");
	}

	public M setInvoiceStatusName(java.lang.String invoiceStatusName) {
		set("invoice_status_name", invoiceStatusName);
		return (M)this;
	}
	
	public java.lang.String getInvoiceStatusName() {
		return getStr("invoice_status_name");
	}

	public M setIssueReceiptCount(java.lang.Integer issueReceiptCount) {
		set("issue_receipt_count", issueReceiptCount);
		return (M)this;
	}
	
	public java.lang.Integer getIssueReceiptCount() {
		return getInt("issue_receipt_count");
	}

	public M setMatchId(java.lang.String matchId) {
		set("match_id", matchId);
		return (M)this;
	}
	
	public java.lang.String getMatchId() {
		return getStr("match_id");
	}

	public M setMatchedAmount(java.math.BigDecimal matchedAmount) {
		set("matched_amount", matchedAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getMatchedAmount() {
		return get("matched_amount");
	}

	public M setMonetaryUnit(java.lang.String monetaryUnit) {
		set("monetary_unit", monetaryUnit);
		return (M)this;
	}
	
	public java.lang.String getMonetaryUnit() {
		return getStr("monetary_unit");
	}

	public M setObjectId(java.lang.String objectId) {
		set("object_id", objectId);
		return (M)this;
	}
	
	public java.lang.String getObjectId() {
		return getStr("object_id");
	}

	public M setObjectType(java.lang.String objectType) {
		set("object_type", objectType);
		return (M)this;
	}
	
	public java.lang.String getObjectType() {
		return getStr("object_type");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	public M setOther(java.lang.String other) {
		set("other", other);
		return (M)this;
	}
	
	public java.lang.String getOther() {
		return getStr("other");
	}

	public M setOverDueFineStatus(java.lang.String overDueFineStatus) {
		set("over_due_fine_status", overDueFineStatus);
		return (M)this;
	}
	
	public java.lang.String getOverDueFineStatus() {
		return getStr("over_due_fine_status");
	}

	public M setOverDueFineStatusName(java.lang.String overDueFineStatusName) {
		set("overDueFineStatusName", overDueFineStatusName);
		return (M)this;
	}
	
	public java.lang.String getOverDueFineStatusName() {
		return getStr("overDueFineStatusName");
	}

	public M setPayDate(java.util.Date payDate) {
		set("pay_date", payDate);
		return (M)this;
	}
	
	public java.util.Date getPayDate() {
		return get("pay_date");
	}

	public M setPayedAmount(java.math.BigDecimal payedAmount) {
		set("payed_amount", payedAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getPayedAmount() {
		return get("payed_amount");
	}

	public M setPrimeAmount(java.math.BigDecimal primeAmount) {
		set("prime_amount", primeAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrimeAmount() {
		return get("prime_amount");
	}

	public M setReceiptAmount(java.math.BigDecimal receiptAmount) {
		set("receipt_amount", receiptAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getReceiptAmount() {
		return get("receipt_amount");
	}

	public M setRemainingAmount(java.math.BigDecimal remainingAmount) {
		set("remaining_amount", remainingAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getRemainingAmount() {
		return get("remaining_amount");
	}

	public M setRoomNumber(java.lang.String roomNumber) {
		set("room_number", roomNumber);
		return (M)this;
	}
	
	public java.lang.String getRoomNumber() {
		return getStr("room_number");
	}

	public M setSettleStatus(java.lang.String settleStatus) {
		set("settle_status", settleStatus);
		return (M)this;
	}
	
	public java.lang.String getSettleStatus() {
		return getStr("settle_status");
	}

	public M setSettleStatusName(java.lang.String settleStatusName) {
		set("settle_status_name", settleStatusName);
		return (M)this;
	}
	
	public java.lang.String getSettleStatusName() {
		return getStr("settle_status_name");
	}

	public M setSettledDate(java.util.Date settledDate) {
		set("settledDate", settledDate);
		return (M)this;
	}
	
	public java.util.Date getSettledDate() {
		return get("settledDate");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}
	
	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setTenantId(java.lang.String tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.String getTenantId() {
		return getStr("tenant_id");
	}

	public M setTermId(java.lang.String termId) {
		set("term_id", termId);
		return (M)this;
	}
	
	public java.lang.String getTermId() {
		return getStr("term_id");
	}

	public M setTerminationIncomeAdjust(java.math.BigDecimal terminationIncomeAdjust) {
		set("termination_income_adjust", terminationIncomeAdjust);
		return (M)this;
	}
	
	public java.math.BigDecimal getTerminationIncomeAdjust() {
		return get("termination_income_adjust");
	}

	public M setTheoryAmount(java.math.BigDecimal theoryAmount) {
		set("theory_amount", theoryAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getTheoryAmount() {
		return get("theory_amount");
	}

	public M setTransferAmount(java.math.BigDecimal transferAmount) {
		set("transfer_amount", transferAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getTransferAmount() {
		return get("transfer_amount");
	}

	public M setTransferToOtherBillAmount(java.math.BigDecimal transferToOtherBillAmount) {
		set("transfer_to_other_bill_amount", transferToOtherBillAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getTransferToOtherBillAmount() {
		return get("transfer_to_other_bill_amount");
	}

	public M setTypeNme(java.lang.String typeNme) {
		set("type_nme", typeNme);
		return (M)this;
	}
	
	public java.lang.String getTypeNme() {
		return getStr("type_nme");
	}

	public M setIsDel(java.lang.String isDel) {
		set("is_del", isDel);
		return (M)this;
	}
	
	public java.lang.String getIsDel() {
		return getStr("is_del");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
		return (M)this;
	}
	
	public java.util.Date getCtime() {
		return get("ctime");
	}

	public M setUtime(java.util.Date utime) {
		set("utime", utime);
		return (M)this;
	}
	
	public java.util.Date getUtime() {
		return get("utime");
	}

}
