package com.topwave.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bill", "bill_id", Bill.class);
		arp.addMapping("bill_cash_flow", "id", BillCashFlow.class);
		arp.addMapping("bill_cash_matches", "id", BillCashMatches.class);
		arp.addMapping("bill_room", "id", BillRoom.class);
		arp.addMapping("building", "building_id", Building.class);
		arp.addMapping("contract", "contract_id", Contract.class);
		arp.addMapping("contract_contact", "contact_id", ContractContact.class);
		arp.addMapping("contract_lease_term", "lease_id", ContractLeaseTerm.class);
		arp.addMapping("contract_room", "id", ContractRoom.class);
		arp.addMapping("floor", "floor_id", Floor.class);
		arp.addMapping("room", "room_id", Room.class);
		arp.addMapping("tenant", "enterprise_id", Tenant.class);
		arp.addMapping("test", "id", Test.class);
		arp.addMapping("user", "user_id", User.class);
	}
}

