package com.topwave.model;

import com.topwave.model.base.BaseBillCashMatches;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BillCashMatches extends BaseBillCashMatches<BillCashMatches> {
	public static final BillCashMatches dao = new BillCashMatches().dao();
}
