package com.topwave.model;

import com.topwave.model.base.BaseBillRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BillRoom extends BaseBillRoom<BillRoom> {
	public static final BillRoom dao = new BillRoom().dao();
}
