package com.topwave.model;

import com.topwave.model.base.BaseBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bill extends BaseBill<Bill> {
	public static final Bill dao = new Bill().dao();
}
