package com.topwave.model;

import com.topwave.model.base.BaseBillCashFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BillCashFlow extends BaseBillCashFlow<BillCashFlow> {
	public static final BillCashFlow dao = new BillCashFlow().dao();
}
