package com.topwave.model;

import com.topwave.model.base.BaseContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contract extends BaseContract<Contract> {
	public static final Contract dao = new Contract().dao();
}
