package com.topwave.model;

import com.topwave.model.base.BaseContractContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractContact extends BaseContractContact<ContractContact> {
	public static final ContractContact dao = new ContractContact().dao();
}
