package com.topwave.model;

import com.topwave.model.base.BaseContractRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractRoom extends BaseContractRoom<ContractRoom> {
	public static final ContractRoom dao = new ContractRoom().dao();
}
