package com.topwave.model;

import com.topwave.model.base.BaseContractLeaseTerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractLeaseTerm extends BaseContractLeaseTerm<ContractLeaseTerm> {
	public static final ContractLeaseTerm dao = new ContractLeaseTerm().dao();
}
