package com.topwave.model;

import com.topwave.model.base.BaseTenant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tenant extends BaseTenant<Tenant> {
	public static final Tenant dao = new Tenant().dao();
}
